name: CI/CD

on: [push, pull_request]

jobs:
    build:
        name: 'Build & Test'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: npm install --global rollup
              run: npm install --global rollup
              env:
                  CI: true
            - name: npm install
              run: npm install
              env:
                  CI: true
            - name: npm run test
              run: npm run test
              env:
                  CI: true
